
services:
  mariadb:
    image: mariadb:10.11
    container_name: sudmaps-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: sudmaps
      MYSQL_USER: suduser
      MYSQL_PASSWORD: sudpass
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: sudmaps-adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mariadb_data:
